version: '3'
services:
  react-compose:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 9000:3000
    volumes:
    - ./src:/usr/src/app/src:delegated
    - ./package.json:/usr/src/app/package.json:delegated